Repository voxpupuli/puppet_metadata, pull requests merged in 2022-06, with the labels that each got.

#42 Release 1.5.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#46 supported_releases: treat OSes with `nil` as EoL date as non-EoL
  lib/puppet_metadata/operatingsystem.rb
  spec/operatingsystem_spec.rb
Labels: bug

#45 Add expected EOL dates for current FreeBSD releases
  lib/puppet_metadata/operatingsystem.rb
Labels: enhancement

#48 Add AlmaLinux and Rocky
  lib/puppet_metadata/operatingsystem.rb
  spec/operatingsystem_spec.rb
Labels: enhancement

#47 Debian 10: Add EoL date
  lib/puppet_metadata/operatingsystem.rb
Labels: enhancement

#52 Revert "Debian 10: Add EoL date"
  lib/puppet_metadata/operatingsystem.rb
Labels: skip-changelog

#53 README.md: Fix internal link to other section
  README.md
Labels: bug

#54 Release 1.7.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog
