Repository voxpupuli/puppet_metadata, pull requests merged in 2023-10, with the labels that each got.

#35 Add a name to the GHA beaker test matrix
  lib/puppet_metadata/github_actions.rb
  spec/github_actions_spec.rb
Labels: enhancement

#105 Release 3.3.0
  CHANGELOG.md
  Rakefile
  puppet_metadata.gemspec
Labels: skip-changelog

#109 Release 3.4.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#102 Add Debian 12
  lib/puppet_metadata/github_actions.rb
  lib/puppet_metadata/operatingsystem.rb
  spec/github_actions_spec.rb
  spec/operatingsystem_spec.rb
Labels: enhancement

#104 Add support for Fedora Distro Puppet testing
  lib/puppet_metadata/github_actions.rb
  lib/puppet_metadata/operatingsystem.rb
  spec/github_actions_spec.rb
Labels: enhancement

#110 Release 3.5.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#34 Document API in README.md
  README.md
Labels: documentation
