Repository voxpupuli/puppet_metadata, pull requests merged in 2024-05, with the labels that each got.

#130 Drop deprecated use_fqdn option and github_action_test_matrix output
  bin/metadata2gha
  lib/puppet_metadata/beaker.rb
  lib/puppet_metadata/github_actions.rb
  spec/beaker_spec.rb
  spec/github_actions_spec.rb
Labels: backwards-incompatible

#131 OracleLinux: Correct EoL Date 2024-07-01->2024-12-31
  lib/puppet_metadata/operatingsystem.rb
Labels: bug

#129 Skip EOL operating systems in GHA acceptance tests
  lib/puppet_metadata/github_actions.rb
  spec/github_actions_spec.rb
Labels: backwards-incompatible

#132 Release 4.0.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#134 AlmaLinux: Update EoL dates
  lib/puppet_metadata/operatingsystem.rb
Labels: enhancement

#135 Rocky: Update EoL dates
  lib/puppet_metadata/operatingsystem.rb
Labels: enhancement
