Repository voxpupuli/puppet_metadata, pull requests merged in 2024-04, with the labels that each got.

#124 Add option to generate setfile with multiple hosts and roles
  README.md
  bin/metadata2gha
  lib/puppet_metadata/beaker.rb
  lib/puppet_metadata/github_actions.rb
  spec/beaker_spec.rb
  spec/github_actions_spec.rb
Labels: enhancement

#125 Release 3.7.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#126 Fix bug in metadata2gha options parsing
  bin/metadata2gha
Labels: bug

#127 Release 3.7.1
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#128 Add Ruby 3.3 to CI
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement
