Repository voxpupuli/puppet_metadata, pull requests merged in 2025-08, with the labels that each got.

#180 Cleanup CI config and apply Vox Pupuli best practices
  .github/release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Gemfile
Labels: skip-changelog

#181 Release 5.1.0
  CHANGELOG.md
  Rakefile
  puppet_metadata.gemspec
Labels: skip-changelog

#183 Release 5.2.0
  CHANGELOG.md
  puppet_metadata.gemspec
Labels: skip-changelog

#187 Correct Enterprise Linux EOL dates & add Fedora 42
  lib/puppet_metadata/operatingsystem.rb
  spec/operatingsystem_spec.rb
Labels: bug

#189 Require Ruby 3.2 or newer
  .rubocop.yml
  .rubocop_todo.yml
  lib/puppet_metadata/beaker.rb
  puppet_metadata.gemspec
Labels: backwards-incompatible
